{{- $adminUser := randAlphaNum 10 -}}
{{- $adminPass := randAlphaNum 25 -}}

apiVersion: v1
kind: Secret
metadata:
  name: postgres-api-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-user: {{ $adminUser | b64enc | quote }}
  postgres-password: {{ $adminPass | b64enc | quote }}

